version: '3.8'

services:
  delivery:
    build:
      context: .
      dockerfile: delivery/.Dockerfile
    ports:
      - "8002:8002"
    networks:
      - cookies_network
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8002"]

  repair:
    build:
      context: .
      dockerfile: repair/.Dockerfile
    ports:
      - "8003:8003"
    networks:
      - cookies_network
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8003"]

  customer-back:
    build:
      context: .
      dockerfile: customer_back/.Dockerfile
    ports:
      - "8001:8001"
    networks:
      - cookies_network
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8001"]

  customer-front:
    build:
      context: .
      dockerfile: customer_front/.Dockerfile
    ports:
      - "80:3000"
    networks:
      - cookies_network
    command: ["npm", "start"]

  websocket-layer:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - cookies_network

  keycloak:
    image: "quay.io/keycloak/keycloak:22.0.1"
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    command: ["start-dev"]

networks:
  cookies_network: